In [7]:
import numpy as np
import pandas as pd

In [8]:
# these matrices generate SL3_Z, according to this paper: https://www.ams.org/journals/proc/1992-115-01/S0002-9939-1992-1079696-5/S0002-9939-1992-1079696-5.pdf

x = np.array([[1, 0, 1], [0, -1, -1], [0, 1, 0]])
y = np.array([[0, 1, 0], [0, 0, 1], [1, 0, 0]])
z = np.array([[0, 1, 0], [1, 0, 0], [-1, -1, -1]])

In [9]:
cols = {
    'val1': [],
    'val2': [],
    'val3' : [],
    'val4': [],
    'val5': [],
    'val6': [],
    'val7' : [],
    'val8': [],
    'val9': []
}

data = pd.DataFrame(cols)

In [10]:
for _ in range(10000):

    first_pos = np.random.randint(0, 3, size=1)[0]

    if first_pos==0:
        start_matrix = x
    elif first_pos==1:
        start_matrix=y
    elif first_pos==2:
        start_matrix=z

    cur_matrix = start_matrix


    a = np.random.randint(0, 3, size=30)
    for i in a: 
        if i==0:
            cur_matrix = cur_matrix @ x
        elif i==1:
            cur_matrix = cur_matrix @ y
        elif i==2:
            cur_matrix = cur_matrix @ z

    df2 = pd.DataFrame([[
            cur_matrix[0][0], 
            cur_matrix[0][1], 
            cur_matrix[0][2],
            cur_matrix[1][0], 
            cur_matrix[1][1], 
            cur_matrix[1][2],
            cur_matrix[2][0], 
            cur_matrix[2][1], 
            cur_matrix[2][2]
            ]],
            columns=['val1', 'val2', 'val3', 'val4', 'val5', 'val6', 'val7', 'val8', 'val9'])
    data = pd.concat([df2, data])

In [11]:
data

    val1  val2  val3  val4  val5  val6  val7  val8  val9
0   -4.0  -2.0  -1.0   2.0   1.0   0.0   1.0   0.0   0.0
0   -1.0   0.0  -1.0  -1.0  -2.0  -2.0   1.0   1.0   2.0
0   -1.0  -1.0   0.0   3.0   0.0  -2.0  -1.0   0.0   1.0
0    0.0   1.0   2.0   1.0   1.0   0.0  -1.0  -1.0  -1.0
0    1.0   0.0   0.0  -1.0  -2.0  -1.0   1.0   1.0   0.0
..   ...   ...   ...   ...   ...   ...   ...   ...   ...
0    1.0   2.0   3.0   0.0  -1.0  -1.0   0.0   0.0  -1.0
0   -1.0  -1.0  -1.0   0.0   1.0   2.0   0.0  -1.0  -3.0
0   -1.0  -1.0   1.0   0.0  -1.0   1.0   1.0   2.0  -1.0
0    1.0   2.0   0.0   1.0  -1.0   1.0  -1.0   0.0  -1.0
0   -1.0  -1.0  -1.0  -1.0   0.0   0.0   2.0   1.0   0.0

[10000 rows x 9 columns]

In [12]:
data.to_csv('sl3_Z_test.csv', index=False)